# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CustomLogMarshaler < Formula
  desc "Attempt to R.I.P PII or unnecessary info in logs and reduce log ingestion costs in the process."
  homepage "https://github.com/solodynamo/custom-log-marshaler"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/solodynamo/custom-log-marshaler/releases/download/v1.1.0/custom-log-marshaler_1.1.0_darwin_arm64.tar.gz"
      sha256 "de7be837cf791c0abd5248998db4092f324a4bc19e45ebb03f1cead0b511c92c"

      def install
        bin.install "custom-log-marshaler"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/solodynamo/custom-log-marshaler/releases/download/v1.1.0/custom-log-marshaler_1.1.0_darwin_amd64.tar.gz"
      sha256 "d23a1ccc400427d2db8852d7cabc18ae8014fb64b1046f48e1a3625c026c0698"

      def install
        bin.install "custom-log-marshaler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/solodynamo/custom-log-marshaler/releases/download/v1.1.0/custom-log-marshaler_1.1.0_linux_amd64.tar.gz"
      sha256 "7823c21e341f8634a7b31e91456c96311fdb36b73b81ae62a7d7280255e29ce2"

      def install
        bin.install "custom-log-marshaler"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/solodynamo/custom-log-marshaler/releases/download/v1.1.0/custom-log-marshaler_1.1.0_linux_arm64.tar.gz"
      sha256 "184fc77e418406bc7d4b384de7f012e0d584cf7d81367e46e695e269fe60055e"

      def install
        bin.install "custom-log-marshaler"
      end
    end
  end

  test do
    system "#{bin}/custom-log-marshaler version"
  end
end
