# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CustomLogMarshaler < Formula
  desc "Attempt to R.I.P PII or unnecessary info in logs and reduce log ingestion costs in the process."
  homepage "https://github.com/solodynamo/custom-log-marshaler"
  version "1.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/solodynamo/custom-log-marshaler/releases/download/v1.0.10/custom-log-marshaler_1.0.10_darwin_amd64.tar.gz"
      sha256 "48d61b241948ea7944c8bfd71f6b9dd8e76bc46a19bddbf02bb8fb195cbef613"

      def install
        bin.install "custom-log-marshaler"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/solodynamo/custom-log-marshaler/releases/download/v1.0.10/custom-log-marshaler_1.0.10_darwin_arm64.tar.gz"
      sha256 "1cbb703a91e8f092f977e250fcaf6605ef226d9a40caa756a09152f363de5c16"

      def install
        bin.install "custom-log-marshaler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/solodynamo/custom-log-marshaler/releases/download/v1.0.10/custom-log-marshaler_1.0.10_linux_arm64.tar.gz"
      sha256 "f2650731a237cad7daec3ab6bc8453f695e319869c9921cabd09f4e29d5c6a6a"

      def install
        bin.install "custom-log-marshaler"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/solodynamo/custom-log-marshaler/releases/download/v1.0.10/custom-log-marshaler_1.0.10_linux_amd64.tar.gz"
      sha256 "de12ccc51d5745cbcadc70058bfc86b3ef7e9597fa8d8c940d5159561e558008"

      def install
        bin.install "custom-log-marshaler"
      end
    end
  end

  test do
    system "#{bin}/custom-log-marshaler version"
  end
end
